language: node_js

node_js:
  - "7"
install:
  - npm install -g mocha
  - npm install
script:
  - npm run --silent build
  - npm run --silent lint
  - npm run --silent test-mocha
  - npm run --silent test-cucumber
